version: "3"

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: condo-access-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  
  db:
    build: .docker/postgres
    container_name: condo-access-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=condo_access

  pgadmin:
    image: dpage/pgadmin4
    container_name: condo-access-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com.br
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
    depends_on:
      - db